import type { Metadata } from 'next'
import LayoutLogin from '@/app/components/Layout/LayoutLogin';


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (

    <LayoutLogin>
      {children}
    </LayoutLogin>

  )
}
